version: "3.8"

services:
  postgres:
    build: "./database"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_POASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    restart: always
  
  nats:
    image: "nats-streaming:0.9.2"
    restart: always